# This file sets the defaults for all ci variables.
# It can and should be used to configure differences between branches.
# It can also be used for feature branches e.g. if not all test are needed or another db should be used.
# overwritten by: ci-config.yml < variables in gitlab-ci.yml < gitlab project variables < per pipeline variables

variables:
  # The major commit ref name is mainly used for ci caching. Non feature branches should be there own major. The major of feature branches should be the branch the will be merged into.
  MAJOR_COMMIT_REF_NAME: "2021.11"

  # main toggle for gitlab ci. if false the ci will do nothing
  RUN_CI_PIPELINE: "true"

  # do not push any images. Commit images will still be pushed. But they are tagged per pipeline
  NO_PUSH: "false"

  # push the built result to docker hub. should be only set to true by schedules. force build all images
  PUSH_TO_DOCKERHUB: "false"

  # push the built image to gitlab. force build built and source image
  PUSH_BUILT_IMAGE_TO_GITLAB: "false"

  # push the dev image to gitlab. force build all images
  PUSH_DEV_IMAGE_TO_GITLAB: "false"

  # tag used on docker hub
  DOCKERHUB_TAG: "dev"

  # whether to build the built image. needed for built tests and docker build dev
  DOCKER_BUILD_BUILD: "false"
  # todo remove this var and run job only if another job requires build.

  # whether to build the dev image. needed for built tests
  DOCKER_BUILD_DEV: "false"
  # todo remove this var and run job only if another job requires build.

  # install one custom app via composer: vendor
  CUSTOM_APP_VENDOR: "metaways"

  # install one custom app via composer: version
  CUSTOM_APP_VERSION: "dev-master"

  # install one custom app via composer: name
  # CUSTOM_APP_NAME default should be nothing

  # install one custom app via composer: git url
  # CUSTOM_APP_GIT_URL default should be nothing

  # enable php stan
  PHP_STAN_ANALYSES: "true"

  # enable or disable php unit tests on source (with webpack) image.
  PHP_UNIT_ALL_TESTS_SOURCE: "true"

  # enable or disable php unit test on built (with built js, and clean files) image.
  PHP_UNIT_ALL_TESTS_BUILT: "false"

  # enable or disable run all test with ldap backend enabled. Not connected with PHP_UNIT_ALL_TESTS_BUILT.
  PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP: "false"

  # enable server tests
  PHP_UNIT_SERVERTESTS: "true"

  # enable or disable php unit setup tests
  PHP_UNIT_SETUP_TESTS: "false"

  # run test with nogitlabci group (test know to not work in gitlab).
  PHP_UNIT_NOGITLABCI_TESTS_BUILT: "false"

  # whether to run source test in parallel or not
  PHP_UNIT_ALL_TESTS_SOURCE_PARALLEL: "true"

  # database image used by tests
  DATABASE_IMAGE: "mariadb:10.4.1"

  # redis image used by tests
  REDIS_IMAGE: "redis:5.0.5"

  # add a php unit filter to all php unit test jobs e.g. "CashBook"
  PHPUNIT_FILTER: ""

  # test if tine20 /health api dose not return a 500
  TEST_WITH_HEALTH_CHECK: "false"
  
  # Run all tests, test failures are ignored, dose not allow push
  RUN_ALL_TESTS: "false"

  # Test if the image was build with the correct php version
  CHECK_PHP_VERSION: "false"

  # php version to use
  PHP_VERSION: "7.3"